name: autoupdate
on:
    push:
        paths:
            - ".github/workflows/**"
jobs:
    autoupdate:
        name: autoupdate
        runs-on: ubuntu-18.04
        steps:
            - uses: docker://chinthakagodawita/autoupdate-action:v1
              env:
                  GITHUB_TOKEN: "${{ secrets.ACCESS_TOKEN }}"
                  MERGE_CONFLICT_ACTION: "ignore"
